terraform{
    required_providers{
        azurerm = {
            source = "hashicorp/azurerm"
            version = "3.47.0"
        }
    }
}

/*
These below SP is generated by running below commands 
az login
az account list
az account set --subscription="20000000-0000-0000-0000-000000000000"
az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/20000000-0000-0000-0000-000000000000"

appId is the client_id defined above.
password is the client_secret defined above.
tenant is the tenant_id defined above.

*/



provider "azurerm" {
  features {}
  client_id       = "fb59d594-47a4-49a1-a7a5-f7f41827eb12"
  client_secret   = "dru8Q~p2AxunIwpcFGsyo23EXsBR0_sRPgD3NbzF"
  tenant_id       = "c6d447ba-b083-44ad-bc01-2f3cf00867e0"
  subscription_id = "9a898369-a5d7-406d-96a6-92a1da784b44"
}

resource "azurerm_resource_group" "terraform-RSG" {
    name = "terraform-RSG"
    location = "centralindia"
}